[package]
name = "html_parser"
version = "0.1.0"
authors = ["Mathias Iversen <work@mathiasiversen.com>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
anyhow = "1.0.30"
thiserror = "1.0.17"

[dev-dependencies]
indoc = "0.3.5"
surf = "1.0.3"
async-std = { version = "1.5.0", features = ["attributes"]}
