[package]
name = "html_parser"
version = "0.1.0"
authors = ["Mathias Iversen <work@mathiasiversen.com>"]
edition = "2018"
repository = "https://github.com/mathiversen/html-parser"
license = "MIT"
description = "A simple and extensible html parser."
keywords = ["html", "parser", "json", "pest", "ast"]
categories = ["parsing", "web-programming"]
readme = "README.md"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
anyhow = "1.0.30"
thiserror = "1.0.17"
serde = "1.0.110"
serde_derive = "1.0.110"
serde_json = "1.0.53"

[dev-dependencies]
indoc = "0.3.5"
surf = "1.0.3"
async-std = { version = "1.5.0", features = ["attributes"]}
insta = "0.16.0"
