[package]
name = "html_parser"
version = "0.1.0"
authors = ["Mathias Iversen <work@mathiasiversen.com>"]
edition = "2018"

[[bin]]
name = "hp-bin"
path = "src/bin.rs"

[lib]
name = "html_parser"
path = "src/lib.rs"

[dependencies]
indoc = "0.3.5"
pest = "2.1.3"
pest_derive = "2.1.0"
anyhow = "1.0.30"
thiserror = "1.0.17"
surf = "1.0.3"
async-std = { version = "1.5.0", features = ["attributes"]}
structopt = "0.3.14"
futures = "0.3.5"
